// @generated by cargo run -p xtask -- theme generate. Do not edit directly.
#![allow(clippy::unreadable_literal)]

use soyuz_sdf::Environment;

pub const RENDER_CLEAR_COLOR: wgpu::Color = wgpu::Color {
    r: 0.101961,
    g: 0.101961,
    b: 0.101961,
    a: 1.0,
};

#[must_use]
pub fn default_environment() -> Environment {
    Environment {
        sun_direction: [0.5, 0.8, 0.3],
        sun_color: [1.0, 0.95, 0.9],
        sun_intensity: 1.2,
        ambient_color: [0.4, 0.5, 0.7],
        ambient_intensity: 0.3,
        material_color: [0.7, 0.7, 0.7],
        material_shininess: 32.0,
        specular_intensity: 0.5,
        sky_horizon: [0.8, 0.85, 0.9],
        sky_zenith: [0.4, 0.6, 0.9],
        fog_color: [0.8, 0.85, 0.9],
        fog_density: 0.0,
        ao_enabled: true,
        ao_intensity: 0.5,
        shadows_enabled: true,
        shadow_softness: 16.0,
    }
}
