// @generated by cargo run -p xtask -- docs generate. Do not edit directly.
#![allow(clippy::missing_panics_doc)]
#![allow(clippy::unwrap_used)]

use rhai::Engine;
use soyuz_sdf::Environment;
use std::sync::{Arc, Mutex};

use crate::env_api;
use crate::sdf_api::{self, RhaiSdf};

pub const API_MANIFEST_JSON: &str = include_str!("../../../SOYUZ_API.json");

pub fn register_sdf_api_generated(engine: &mut Engine) {
    engine
        .register_type_with_name::<RhaiSdf>("Sdf")
        .register_fn("to_string", |sdf: &mut RhaiSdf| format!("{:?}", sdf.op));
    engine.register_fn("sphere", sdf_api::sphere);
    engine.register_fn("sphere", sdf_api::sphere_int);
    engine.register_fn("cube", sdf_api::cube);
    engine.register_fn("cube", sdf_api::cube_int);
    engine.register_fn("box3", sdf_api::box3);
    engine.register_fn("rounded_box", sdf_api::rounded_box);
    engine.register_fn("cylinder", sdf_api::cylinder);
    engine.register_fn("capsule", sdf_api::capsule);
    engine.register_fn("torus", sdf_api::torus);
    engine.register_fn("cone", sdf_api::cone);
    engine.register_fn("plane", sdf_api::plane);
    engine.register_fn("ground_plane", sdf_api::ground_plane);
    engine.register_fn("ellipsoid", sdf_api::ellipsoid);
    engine.register_fn("octahedron", sdf_api::octahedron);
    engine.register_fn("hex_prism", sdf_api::hex_prism);
    engine.register_fn("tri_prism", sdf_api::tri_prism);
    engine.register_fn("pyramid", sdf_api::pyramid);
    engine.register_fn("link", sdf_api::link);
    engine.register_fn("extrude_circle", sdf_api::extrude_circle);
    engine.register_fn("extrude_rect", sdf_api::extrude_rect);
    engine.register_fn("extrude_rounded_rect", sdf_api::extrude_rounded_rect);
    engine.register_fn("revolve_circle", sdf_api::revolve_circle);
    engine.register_fn("revolve_rect", sdf_api::revolve_rect);
    engine.register_fn("union", RhaiSdf::union);
    engine.register_fn("subtract", RhaiSdf::subtract);
    engine.register_fn("intersect", RhaiSdf::intersect);
    engine.register_fn("smooth_union", RhaiSdf::smooth_union);
    engine.register_fn("smooth_subtract", RhaiSdf::smooth_subtract);
    engine.register_fn("smooth_intersect", RhaiSdf::smooth_intersect);
    engine.register_fn("xor", RhaiSdf::xor);
    engine.register_fn("shell", RhaiSdf::shell);
    engine.register_fn("hollow", RhaiSdf::hollow);
    engine.register_fn("round", RhaiSdf::round);
    engine.register_fn("onion", RhaiSdf::onion);
    engine.register_fn("elongate", RhaiSdf::elongate);
    engine.register_fn("twist", RhaiSdf::twist);
    engine.register_fn("bend", RhaiSdf::bend);
    engine.register_fn("displace", RhaiSdf::displace);
    engine.register_fn("repeat", RhaiSdf::repeat);
    engine.register_fn("repeat_limited", RhaiSdf::repeat_limited);
    engine.register_fn("repeat_polar", RhaiSdf::repeat_polar);
    engine.register_fn("translate", RhaiSdf::translate);
    engine.register_fn("translate_x", RhaiSdf::translate_x);
    engine.register_fn("translate_y", RhaiSdf::translate_y);
    engine.register_fn("translate_z", RhaiSdf::translate_z);
    engine.register_fn("rotate_x", RhaiSdf::rotate_x);
    engine.register_fn("rotate_y", RhaiSdf::rotate_y);
    engine.register_fn("rotate_z", RhaiSdf::rotate_z);
    engine.register_fn("scale", RhaiSdf::scale);
    engine.register_fn("mirror_x", RhaiSdf::mirror_x);
    engine.register_fn("mirror_y", RhaiSdf::mirror_y);
    engine.register_fn("mirror_z", RhaiSdf::mirror_z);
    engine.register_fn("symmetry_x", RhaiSdf::symmetry_x);
    engine.register_fn("symmetry_y", RhaiSdf::symmetry_y);
    engine.register_fn("symmetry_z", RhaiSdf::symmetry_z);
    engine.register_fn("PI", sdf_api::pi);
    engine.register_fn("TAU", sdf_api::tau);
    engine.register_fn("deg", sdf_api::deg_to_rad);
    engine.register_fn("rad", sdf_api::rad_to_deg);
}

#[allow(clippy::too_many_lines)]
pub fn register_env_api_generated(engine: &mut Engine, env: &Arc<Mutex<Environment>>) {
    let e = env.clone();
    engine.register_fn("set_sun_direction", move |x: f64, y: f64, z: f64| {
        e.lock().unwrap().sun_direction = [x as f32, y as f32, z as f32];
    });
    let e = env.clone();
    engine.register_fn("set_sun_color", move |x: f64, y: f64, z: f64| {
        e.lock().unwrap().sun_color = [x as f32, y as f32, z as f32];
    });
    let e = env.clone();
    engine.register_fn("set_sun_intensity", move |value: f64| {
        e.lock().unwrap().sun_intensity = value as f32;
    });
    let e = env.clone();
    engine.register_fn("set_ambient_color", move |x: f64, y: f64, z: f64| {
        e.lock().unwrap().ambient_color = [x as f32, y as f32, z as f32];
    });
    let e = env.clone();
    engine.register_fn("set_ambient_intensity", move |value: f64| {
        e.lock().unwrap().ambient_intensity = value as f32;
    });
    let e = env.clone();
    engine.register_fn("set_material_color", move |x: f64, y: f64, z: f64| {
        e.lock().unwrap().material_color = [x as f32, y as f32, z as f32];
    });
    let e = env.clone();
    engine.register_fn("set_material_color_hex", move |hex: &str| {
        if let Some((r, g, b)) = env_api::parse_hex_color(hex) {
            e.lock().unwrap().material_color = [r, g, b];
        }
    });
    let e = env.clone();
    engine.register_fn("set_material_shininess", move |value: f64| {
        e.lock().unwrap().material_shininess = value as f32;
    });
    let e = env.clone();
    engine.register_fn("set_specular_intensity", move |value: f64| {
        e.lock().unwrap().specular_intensity = value as f32;
    });
    let e = env.clone();
    engine.register_fn("set_sky_horizon", move |x: f64, y: f64, z: f64| {
        e.lock().unwrap().sky_horizon = [x as f32, y as f32, z as f32];
    });
    let e = env.clone();
    engine.register_fn("set_sky_zenith", move |x: f64, y: f64, z: f64| {
        e.lock().unwrap().sky_zenith = [x as f32, y as f32, z as f32];
    });
    let e = env.clone();
    engine.register_fn("set_background_color", move |r: f64, g: f64, b: f64| {
        let color = [r as f32, g as f32, b as f32];
        let mut e = e.lock().unwrap();
        e.sky_horizon = color;
        e.sky_zenith = color;
    });
    let e = env.clone();
    engine.register_fn("set_fog_color", move |x: f64, y: f64, z: f64| {
        e.lock().unwrap().fog_color = [x as f32, y as f32, z as f32];
    });
    let e = env.clone();
    engine.register_fn("set_fog_density", move |value: f64| {
        e.lock().unwrap().fog_density = value as f32;
    });
    let e = env.clone();
    engine.register_fn("set_ao_enabled", move |enabled: bool| {
        e.lock().unwrap().ao_enabled = enabled;
    });
    let e = env.clone();
    engine.register_fn("set_ao_intensity", move |value: f64| {
        e.lock().unwrap().ao_intensity = value as f32;
    });
    let e = env.clone();
    engine.register_fn("set_shadows_enabled", move |enabled: bool| {
        e.lock().unwrap().shadows_enabled = enabled;
    });
    let e = env.clone();
    engine.register_fn("set_shadow_softness", move |value: f64| {
        e.lock().unwrap().shadow_softness = value as f32;
    });
    engine.register_fn("rgb_hex", env_api::rgb_hex);
    let e = env.clone();
    engine.register_fn("env_default", move || {
        *e.lock().unwrap() = Environment::default();
    });
    let e = env.clone();
    engine.register_fn("env_studio", move || {
        let mut e = e.lock().unwrap();
        e.sun_direction = [1.0, 1.0, 0.5];
        e.sun_color = [1.0, 1.0, 1.0];
        e.sun_intensity = 0.8;
        e.ambient_color = [0.3, 0.3, 0.35];
        e.ambient_intensity = 1.0;
        e.sky_horizon = [0.9, 0.9, 0.95];
        e.sky_zenith = [0.8, 0.85, 0.95];
        e.fog_color = [0.85, 0.85, 0.9];
        e.fog_density = 0.005;
    });
    let e = env.clone();
    engine.register_fn("env_sunset", move || {
        let mut e = e.lock().unwrap();
        e.sun_direction = [1.0, 0.2, 0.3];
        e.sun_color = [1.0, 0.6, 0.3];
        e.sun_intensity = 1.2;
        e.ambient_color = [0.3, 0.2, 0.3];
        e.ambient_intensity = 0.8;
        e.sky_horizon = [1.0, 0.7, 0.5];
        e.sky_zenith = [0.4, 0.3, 0.5];
        e.fog_color = [0.9, 0.6, 0.4];
        e.fog_density = 0.02;
    });
    let e = env.clone();
    engine.register_fn("env_night", move || {
        let mut e = e.lock().unwrap();
        e.sun_direction = [0.5, 0.8, 0.2];
        e.sun_color = [0.7, 0.8, 1.0];
        e.sun_intensity = 0.3;
        e.ambient_color = [0.05, 0.07, 0.15];
        e.ambient_intensity = 1.0;
        e.sky_horizon = [0.1, 0.1, 0.2];
        e.sky_zenith = [0.02, 0.02, 0.08];
        e.fog_color = [0.05, 0.05, 0.1];
        e.fog_density = 0.03;
    });
    let e = env.clone();
    engine.register_fn("env_daylight", move || {
        let mut e = e.lock().unwrap();
        e.sun_direction = [0.5, 0.8, 0.3];
        e.sun_color = [1.0, 0.98, 0.95];
        e.sun_intensity = 1.0;
        e.ambient_color = [0.2, 0.25, 0.35];
        e.ambient_intensity = 1.0;
        e.sky_horizon = [0.7, 0.8, 0.9];
        e.sky_zenith = [0.3, 0.5, 0.8];
        e.fog_color = [0.6, 0.65, 0.7];
        e.fog_density = 0.01;
    });
    let e = env.clone();
    engine.register_fn("env_clay", move || {
        let mut e = e.lock().unwrap();
        e.sun_direction = [0.5, 1.0, 0.5];
        e.sun_color = [1.0, 1.0, 1.0];
        e.sun_intensity = 0.6;
        e.ambient_color = [0.5, 0.5, 0.5];
        e.ambient_intensity = 1.0;
        e.material_color = [0.85, 0.85, 0.85];
        e.material_shininess = 8.0;
        e.specular_intensity = 0.1;
        e.shadows_enabled = false;
        e.ao_enabled = true;
        e.ao_intensity = 2.0;
        e.sky_horizon = [0.95, 0.95, 0.95];
        e.sky_zenith = [0.9, 0.9, 0.95];
        e.fog_density = 0.0;
    });
}
